import { Providers } from "@/stores";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <header className="border-b border-b-gray-500 mb-5">
            <div className="max-w-[1260px] w-full mx-auto ">
              <nav className="py-2">
                <ul className="flex list-none gap-5">
                  <li>
                    <Link href={"/customer"}>Customer</Link>
                  </li>
                  <li>
                    <Link href={"/blogs"}>Blogs</Link>
                  </li>
                  <li>
                    <Link href={"/swr-fetch"}>Fetcher SWR</Link>
                  </li>
                  <li>
                    <Link href={"/caching"}>Caching</Link>
                  </li>
                  <li>
                    <Link href={"/params-query"}>Params</Link>
                  </li>
                  <li>
                    <Link href={"/parallel-dashboard"}>Parallel Dashboard</Link>
                  </li>
                  <li>
                    <Link href={"/self"}>Self</Link>
                  </li>
                </ul>
              </nav>
            </div>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
